# -*- coding: utf-8 -*-
"""TDD tests for the ITC-99 BLIF converter (N31-05 generalization prep)."""
from __future__ import annotations

import importlib.util
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "convert_itc99_blif_to_v.py"


def _load():
    sys.path.insert(0, str(ROOT / "scripts"))
    spec = importlib.util.spec_from_file_location("convert_itc99_blif_to_v", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# Realistic yosys 0.9 output shape for b01 after read_blif+techmap (excerpt)
RAW_SAMPLE = r"""/* Generated by Yosys */
module \b01.blif (LINE1, LINE2, OUTP, OVERFLW);
  input LINE1;
  input LINE2;
  output OUTP;
  wire OUTP_REG;
  \$_FF_  _228_ (
    .D(U34),
    .Q(OVERFLW_REG)
  );
  assign _079_[0] = STATO_REG_1_ ? 1'h0 : 1'h0;
  assign OUTP = OUTP_REG;
endmodule
"""


class NormalizeModuleNameTest(unittest.TestCase):
    def test_renames_escaped_model(self):
        mod = _load()
        text = mod.normalize_module_name(RAW_SAMPLE)
        self.assertIn("module b01 (LINE1", text)
        self.assertNotIn("module \\b01.blif", text)


class AddClockPortTest(unittest.TestCase):
    def test_adds_ck_port_and_input(self):
        mod = _load()
        text = mod.normalize_module_name(RAW_SAMPLE)
        text = mod.add_clock_port(text)
        self.assertIn("module b01 (CK, LINE1", text)
        self.assertIn("input CK;", text)

    def test_skips_when_clock_exists(self):
        mod = _load()
        src = "module b01 (CK, A);\n  input CK;\n  input A;\nendmodule\n"
        self.assertEqual(mod.add_clock_port(src), src)


class ClockFfsTest(unittest.TestCase):
    def test_rewrites_ff_to_behavioral_dff(self):
        mod = _load()
        text = mod.clock_ffs(RAW_SAMPLE)
        self.assertIn("dff _228_ (CK, U34, OVERFLW_REG);", text)
        self.assertNotIn("$_FF_", text)
        self.assertIn("module dff", text)
        self.assertIn("always @(posedge CK) Q <= D;", text)

    def test_raises_on_unparseable_ff(self):
        mod = _load()
        with self.assertRaises(ValueError):
            mod.clock_ffs("$_FF_ weird_thing;")


@unittest.skipUnless(shutil.which("yosys"), "requires yosys")
class ConvertEndToEndTest(unittest.TestCase):
    def test_convert_tiny_blif_and_synth(self):
        mod = _load()
        tmp = Path(tempfile.mkdtemp())
        blif = tmp / "mini.blif"
        blif.write_text(
            ".model mini.blif\n"
            ".inputs D\n"
            ".outputs Q\n"
            ".latch D Q 0\n"
            ".names D Q\n"
            "1 1\n"
            ".end\n",
            encoding="utf-8",
        )
        out = tmp / "mini.v"
        text = mod.convert_blif(blif, out)
        self.assertIn("module mini (CK,", text)
        self.assertIn("input CK;", text)
        self.assertIn("dff _0_ (CK, D, Q);", text)
        self.assertIn("module dff", text)
        # synth must digest the behavioral dff helper (proves the
        # clock-free $_FF_ issue is fixed end-to-end)
        proc = subprocess.run(
            ["yosys", "-q", "-p",
             f"read_verilog {out.as_posix()}; synth -top mini"],
            capture_output=True, text=True, encoding="utf-8",
            errors="replace", timeout=120,
        )
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)

    def test_convert_blif_missing_end_terminator(self):
        # b18/b19 in the ITC-99 distribution are truncated without .end
        mod = _load()
        tmp = Path(tempfile.mkdtemp())
        blif = tmp / "mini.blif"
        blif.write_text(
            ".model mini.blif\n"
            ".inputs D\n"
            ".outputs Q\n"
            ".latch D Q 0\n"
            ".names D Q\n"
            "1 1\n",
            encoding="utf-8",
        )
        out = tmp / "mini.v"
        text = mod.convert_blif(blif, out)
        self.assertIn("module mini (CK,", text)
        self.assertIn("dff _0_ (CK, D, Q);", text)
        self.assertFalse((tmp / "mini.fixed.blif").exists(),
                         "temporary fixed blif should be cleaned up")


@unittest.skipUnless(shutil.which("yosys"), "requires yosys")
class ConvertAllTest(unittest.TestCase):
    def test_only_converts_listed(self):
        mod = _load()
        tmp = Path(tempfile.mkdtemp())
        src = tmp / "in"
        src.mkdir()
        body_b01 = (
            ".model b01.blif\n.inputs A\n.outputs Q\n"
            ".latch A Q 0\n.names A Q\n1 1\n.end\n"
        )
        body_b02 = (
            ".model b02.blif\n.inputs A\n.outputs Q\n"
            ".latch A Q 0\n.names A Q\n1 1\n.end\n"
        )
        (src / "b01.blif").write_text(body_b01, encoding="utf-8")
        (src / "b02.blif").write_text(body_b02, encoding="utf-8")
        out = tmp / "out"
        results, errors = mod.convert_all(src, out, only=["b01"])
        self.assertEqual(results, {"b01": "ok"})
        self.assertEqual(errors, [])
        self.assertTrue((out / "b01.v").exists())
        self.assertFalse((out / "b02.v").exists())


if __name__ == "__main__":
    unittest.main()