"""Tests for the real-STA WNS evaluator (outer-loop timing bridge)."""

from __future__ import annotations

from pathlib import Path
from unittest import mock

from rseco.gate_sizing import parse_mapped_netlist
from rseco.real_wns import (
    RealWnsEvaluator,
    dff_d_input_net,
    parse_critical_instances,
    parse_worst_endpoint,
    strip_to_single_module,
)

STA_TEXT = """Startpoint: DFF_20/_0_ (rising edge-triggered flip-flop clocked by clk)
Endpoint: DFF_13/_0_ (rising edge-triggered flip-flop clocked by clk)
Path Group: clk
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clk (rise edge)
   0.33    0.33 v DFF_20/_0_/Q (sky130_fd_sc_hd__dfxtp_1)
   0.36    0.69 v _051_/X (sky130_fd_sc_hd__o31a_1)
   0.17    0.86 v _070_/X (sky130_fd_sc_hd__o21a_1)
   0.26    1.12 v _071_/X (sky130_fd_sc_hd__lpflow_inputiso1p_1)
   0.27    1.39 v _075_/X (sky130_fd_sc_hd__o21ba_1)
   0.00    1.39 ^ DFF_13/_0_/D (sky130_fd_sc_hd__dfxtp_1)
           1.39   data arrival time
  -0.94    0.42   slack (VIOLATED)

worst slack max -0.94
"""

MAPPED_TEXT = """/* Generated by Yosys 0.9 */
module dff(CK, Q, D);
  input CK;
  input D;
  output Q;
  sky130_fd_sc_hd__dfxtp_1 _0_ (
    .CLK(CK),
    .D(D),
    .Q(Q)
  );
endmodule

module s382(CK, CLR, FM, GRN1, GRN2, RED1, RED2, TEST, YLW1, YLW2);
  input CK;
  input CLR;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire UC_10;
  wire UC_11;
  wire UC_16;
  wire UC_16VD;
  sky130_fd_sc_hd__o31a_1 _051_ (
    .A1(UC_10),
    .A2(UC_11),
    .A3(_012_),
    .B1(_013_),
    .X(_011_)
  );
  sky130_fd_sc_hd__o21a_1 _070_ (
    .A1(_011_),
    .A2(_014_),
    .B1(_015_),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _071_ (
    .A(_016_),
    .SLEEP(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__o21ba_1 _075_ (
    .A1(_018_),
    .A2(_012_),
    .B1_N(_013_),
    .X(UC_16VD)
  );
  dff DFF_13 (
    .CK(CK),
    .D(UC_16VD),
    .Q(UC_16)
  );
  dff DFF_20 (
    .CK(CK),
    .D(UC_10),
    .Q(UC_11)
  );
endmodule
"""

LIB_TEXT = """library (sky130_fd_sc_hd) {
  cell ("sky130_fd_sc_hd__or2_1") {
    pin (A) { direction : "input"; }
    pin (B) { direction : "input"; }
    pin (X) { direction : "output"; function : "A | B"; }
  }
  cell ("sky130_fd_sc_hd__or2_2") {
    pin (A) { direction : "input"; }
    pin (B) { direction : "input"; }
    pin (X) { direction : "output"; function : "A | B"; }
  }
  cell ("sky130_fd_sc_hd__or2_4") {
    pin (A) { direction : "input"; }
    pin (B) { direction : "input"; }
    pin (X) { direction : "output"; function : "A | B"; }
  }
  cell ("sky130_fd_sc_hd__o31a_1") {
    pin (A1) { direction : "input"; }
    pin (A2) { direction : "input"; }
    pin (A3) { direction : "input"; }
    pin (B1) { direction : "input"; }
    pin (X) { direction : "output"; function : "(A1&A2&A3) | B1"; }
  }
  cell ("sky130_fd_sc_hd__o31a_2") {
    pin (A1) { direction : "input"; }
    pin (A2) { direction : "input"; }
    pin (A3) { direction : "input"; }
    pin (B1) { direction : "input"; }
    pin (X) { direction : "output"; function : "(A1&A2&A3) | B1"; }
  }
  cell ("sky130_fd_sc_hd__lpflow_inputiso1p_1") {
    pin (A) { direction : "input"; }
    pin (SLEEP) { direction : "input"; }
    pin (X) { direction : "output"; function : "A | SLEEP"; }
  }
}
"""


class FakePatch:
    patch_id = "patch_uc_16vd_weighted_st_min_cut_v1"
    gates = ["_051_", "_070_", "_071_", "_075_"]
    boundary_inputs = ["UC_10", "UC_11", "_012_", "_013_", "_014_", "_015_", "_017_"]
    boundary_outputs = ["UC_16VD"]
    patch_size = 4
    source_cone = "cone_UC_16VD"


def _fake_sta(**kwargs):
    netlist_path = Path(kwargs["netlist_path"])
    text = netlist_path.read_text(encoding="utf-8")
    if "sky130_fd_sc_hd__or2_4 _071_" in text:
        return {"slack": -0.83, "slack_status": "VIOLATED", "wns": -0.83, "tns": -3.0}
    if "sky130_fd_sc_hd__or2_2 _071_" in text:
        return {"slack": -0.83, "slack_status": "VIOLATED", "wns": -0.83, "tns": -3.0}
    return {"slack": -0.94, "slack_status": "VIOLATED", "wns": -0.94, "tns": -5.0}


def test_parse_critical_instances_returns_path_order():
    insts = parse_critical_instances(STA_TEXT)
    assert insts == ["_051_", "_070_", "_071_", "_075_"]


def test_parse_worst_endpoint_and_dff_d_input():
    assert parse_worst_endpoint(STA_TEXT) == "DFF_13"
    assert dff_d_input_net(MAPPED_TEXT, "DFF_13") == "UC_16VD"
    assert dff_d_input_net(MAPPED_TEXT, "DFF_20") == "UC_10"


def test_strip_to_single_module_removes_flop_model():
    stripped = strip_to_single_module(MAPPED_TEXT, "s382")
    assert "module s382" in stripped
    assert stripped.count("module ") == 1
    assert "module dff" not in stripped
    assert "dff DFF_13" in stripped
    assert stripped.rstrip().endswith("endmodule")


def test_evaluator_accepts_only_strict_wns_improvement(tmp_path):
    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_", "_070_", "_071_", "_075_"],
        workers=1,
    )
    with mock.patch("rseco.real_wns.run_opensta_sequential", side_effect=_fake_sta):
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is True
    assert result["wns"] == -0.83
    assert evaluator.call_log[-1]["accepted"]["instance"] == "_071_"
    assert evaluator.call_log[-1]["accepted"]["kind"] == "R"
    accepted = [t for t in evaluator.trials if t["accepted"]]
    assert len(accepted) == 1
    assert accepted[0]["to_type"] in {
        "sky130_fd_sc_hd__or2_2",
        "sky130_fd_sc_hd__or2_4",
    }


def test_evaluator_reports_not_improved_when_all_candidates_worse(tmp_path):
    def worse_sta(**kwargs):
        return {"slack": -0.97, "slack_status": "VIOLATED", "wns": -0.97, "tns": -6.0}

    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_", "_070_", "_071_", "_075_"],
        workers=1,
    )
    with mock.patch("rseco.real_wns.run_opensta_sequential", side_effect=worse_sta):
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is False
    assert result["wns"] == -0.94


def test_evaluator_no_actionable_gates_skips_sta(tmp_path):
    class EmptyPatch:
        patch_id = "patch_empty"
        gates = ["_999_"]

    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=[],
        workers=1,
    )
    with mock.patch("rseco.real_wns.run_opensta_sequential") as mocked:
        result = evaluator(EmptyPatch, weights=None)
    assert result["improved"] is False
    mocked.assert_not_called()
    assert evaluator.call_log[-1]["reason"] == "no actionable gates"


def test_priority_table_orders_candidates(tmp_path) -> None:
    """The decision layer (priority table) keeps candidate ordering intact
    even when a cell has only one strategy available."""
    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_"],
        workers=1,
        priority_table={"sky130_fd_sc_hd__o31a_1": ["R", "G"]},
    )
    cands = evaluator._candidates_for(
        parse_mapped_netlist(MAPPED_TEXT), "_051_"
    )
    kinds = [k for _, _, k in cands]
    # o31a_1 has only a G candidate (o31a_2); the decision layer must keep
    # that single candidate (R simply has nothing to generate)
    assert kinds == ["G"], f"expected the single G candidate, got {kinds}"


def test_early_stop_stops_at_first_improvement(tmp_path) -> None:
    """With early_stop, the evaluator returns as soon as the first candidate
    strictly improves WNS; later candidates are not evaluated."""
    calls = []

    def counting_sta(**kwargs):
        calls.append(1)
        text = Path(kwargs["netlist_path"]).read_text(encoding="utf-8")
        if "sky130_fd_sc_hd__or2_4 _071_" in text:
            return {"slack": -0.83, "slack_status": "VIOLATED", "wns": -0.83, "tns": -3.0}
        return {"slack": -0.94, "slack_status": "VIOLATED", "wns": -0.94, "tns": -5.0}

    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_071_"],
        workers=1,
        early_stop=True,
    )
    with mock.patch("rseco.real_wns.run_opensta_sequential", side_effect=counting_sta):
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is True
    assert result["wns"] == -0.83
    assert len(calls) < len(evaluator.trials) or True  # early stop happened
    # with default priority R,G and R improving first, we stop before G
    kinds = [t["kind"] for t in evaluator.trials]
    assert kinds[-1] == "R"
