"""Tests for the real-STA WNS evaluator (outer-loop timing bridge)."""

from __future__ import annotations

from pathlib import Path
from unittest import mock

from rseco.gate_sizing import parse_mapped_netlist
from rseco.real_wns import (
    RealWnsEvaluator,
    dff_d_input_net,
    parse_critical_instances,
    parse_worst_endpoint,
    strip_to_single_module,
)

STA_TEXT = """Startpoint: DFF_20/_0_ (rising edge-triggered flip-flop clocked by clk)
Endpoint: DFF_13/_0_ (rising edge-triggered flip-flop clocked by clk)
Path Group: clk
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clk (rise edge)
   0.33    0.33 v DFF_20/_0_/Q (sky130_fd_sc_hd__dfxtp_1)
   0.36    0.69 v _051_/X (sky130_fd_sc_hd__o31a_1)
   0.17    0.86 v _070_/X (sky130_fd_sc_hd__o21a_1)
   0.26    1.12 v _071_/X (sky130_fd_sc_hd__lpflow_inputiso1p_1)
   0.27    1.39 v _075_/X (sky130_fd_sc_hd__o21ba_1)
   0.00    1.39 ^ DFF_13/_0_/D (sky130_fd_sc_hd__dfxtp_1)
           1.39   data arrival time
  -0.94    0.42   slack (VIOLATED)

worst slack max -0.94
"""

MAPPED_TEXT = """/* Generated by Yosys 0.9 */
module dff(CK, Q, D);
  input CK;
  input D;
  output Q;
  sky130_fd_sc_hd__dfxtp_1 _0_ (
    .CLK(CK),
    .D(D),
    .Q(Q)
  );
endmodule

module s382(CK, CLR, FM, GRN1, GRN2, RED1, RED2, TEST, YLW1, YLW2);
  input CK;
  input CLR;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire UC_10;
  wire UC_11;
  wire UC_16;
  wire UC_16VD;
  sky130_fd_sc_hd__o31a_1 _051_ (
    .A1(UC_10),
    .A2(UC_11),
    .A3(_012_),
    .B1(_013_),
    .X(_011_)
  );
  sky130_fd_sc_hd__o21a_1 _070_ (
    .A1(_011_),
    .A2(_014_),
    .B1(_015_),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _071_ (
    .A(_016_),
    .SLEEP(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__o21ba_1 _075_ (
    .A1(_018_),
    .A2(_012_),
    .B1_N(_013_),
    .X(UC_16VD)
  );
  dff DFF_13 (
    .CK(CK),
    .D(UC_16VD),
    .Q(UC_16)
  );
  dff DFF_20 (
    .CK(CK),
    .D(UC_10),
    .Q(UC_11)
  );
endmodule
"""

LIB_TEXT = """library (sky130_fd_sc_hd) {
  cell ("sky130_fd_sc_hd__or2_1") {
    pin (A) { direction : "input"; }
    pin (B) { direction : "input"; }
    pin (X) { direction : "output"; function : "A | B"; }
  }
  cell ("sky130_fd_sc_hd__or2_2") {
    pin (A) { direction : "input"; }
    pin (B) { direction : "input"; }
    pin (X) { direction : "output"; function : "A | B"; }
  }
  cell ("sky130_fd_sc_hd__or2_4") {
    pin (A) { direction : "input"; }
    pin (B) { direction : "input"; }
    pin (X) { direction : "output"; function : "A | B"; }
  }
  cell ("sky130_fd_sc_hd__o31a_1") {
    pin (A1) { direction : "input"; }
    pin (A2) { direction : "input"; }
    pin (A3) { direction : "input"; }
    pin (B1) { direction : "input"; }
    pin (X) { direction : "output"; function : "(A1&A2&A3) | B1"; }
  }
  cell ("sky130_fd_sc_hd__o31a_2") {
    pin (A1) { direction : "input"; }
    pin (A2) { direction : "input"; }
    pin (A3) { direction : "input"; }
    pin (B1) { direction : "input"; }
    pin (X) { direction : "output"; function : "(A1&A2&A3) | B1"; }
  }
  cell ("sky130_fd_sc_hd__lpflow_inputiso1p_1") {
    pin (A) { direction : "input"; }
    pin (SLEEP) { direction : "input"; }
    pin (X) { direction : "output"; function : "A | SLEEP"; }
  }
}
"""


class FakePatch:
    patch_id = "patch_uc_16vd_weighted_st_min_cut_v1"
    gates = ["_051_", "_070_", "_071_", "_075_"]
    boundary_inputs = ["UC_10", "UC_11", "_012_", "_013_", "_014_", "_015_", "_017_"]
    boundary_outputs = ["UC_16VD"]
    patch_size = 4
    source_cone = "cone_UC_16VD"


def _fake_sta(**kwargs):
    netlist_path = Path(kwargs["netlist_path"])
    text = netlist_path.read_text(encoding="utf-8")
    if "sky130_fd_sc_hd__or2_4 _071_" in text:
        return {"slack": -0.83, "slack_status": "VIOLATED", "wns": -0.83, "tns": -3.0}
    if "sky130_fd_sc_hd__or2_2 _071_" in text:
        return {"slack": -0.83, "slack_status": "VIOLATED", "wns": -0.83, "tns": -3.0}
    return {"slack": -0.94, "slack_status": "VIOLATED", "wns": -0.94, "tns": -5.0}


def test_parse_critical_instances_returns_path_order():
    insts = parse_critical_instances(STA_TEXT)
    assert insts == ["_051_", "_070_", "_071_", "_075_"]


def test_parse_worst_endpoint_and_dff_d_input():
    assert parse_worst_endpoint(STA_TEXT) == "DFF_13"
    assert dff_d_input_net(MAPPED_TEXT, "DFF_13") == "UC_16VD"
    assert dff_d_input_net(MAPPED_TEXT, "DFF_20") == "UC_10"


def test_strip_to_single_module_removes_flop_model():
    stripped = strip_to_single_module(MAPPED_TEXT, "s382")
    assert "module s382" in stripped
    assert stripped.count("module ") == 1
    assert "module dff" not in stripped
    assert "dff DFF_13" in stripped
    assert stripped.rstrip().endswith("endmodule")


def test_evaluator_accepts_only_strict_wns_improvement(tmp_path):
    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_", "_070_", "_071_", "_075_"],
        workers=1,
    )
    with mock.patch("rseco.real_wns.run_opensta_sequential", side_effect=_fake_sta):
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is True
    assert result["wns"] == -0.83
    assert evaluator.call_log[-1]["accepted"]["instance"] == "_071_"
    assert evaluator.call_log[-1]["accepted"]["kind"] == "R"
    accepted = [t for t in evaluator.trials if t["accepted"]]
    assert len(accepted) == 1
    assert accepted[0]["to_type"] in {
        "sky130_fd_sc_hd__or2_2",
        "sky130_fd_sc_hd__or2_4",
    }


def test_evaluator_reports_not_improved_when_all_candidates_worse(tmp_path):
    def worse_sta(**kwargs):
        return {"slack": -0.97, "slack_status": "VIOLATED", "wns": -0.97, "tns": -6.0}

    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_", "_070_", "_071_", "_075_"],
        workers=1,
    )
    with mock.patch("rseco.real_wns.run_opensta_sequential", side_effect=worse_sta):
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is False
    assert result["wns"] == -0.94


def test_evaluator_no_actionable_gates_skips_sta(tmp_path):
    class EmptyPatch:
        patch_id = "patch_empty"
        gates = ["_999_"]

    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=[],
        workers=1,
    )
    with mock.patch("rseco.real_wns.run_opensta_sequential") as mocked:
        result = evaluator(EmptyPatch, weights=None)
    assert result["improved"] is False
    mocked.assert_not_called()
    assert evaluator.call_log[-1]["reason"] == "no actionable gates"


def test_priority_table_orders_candidates(tmp_path) -> None:
    """The decision layer (priority table) keeps candidate ordering intact
    even when a cell has only one strategy available."""
    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_"],
        workers=1,
        priority_table={"sky130_fd_sc_hd__o31a_1": ["R", "G"]},
    )
    cands = evaluator._candidates_for(
        parse_mapped_netlist(MAPPED_TEXT), "_051_"
    )
    kinds = [k for _, _, k in cands]
    # o31a_1 has only a G candidate (o31a_2); the decision layer must keep
    # that single candidate (R simply has nothing to generate)
    assert kinds == ["G"], f"expected the single G candidate, got {kinds}"


def test_early_stop_stops_at_first_improvement(tmp_path) -> None:
    """With early_stop, the evaluator returns as soon as the first candidate
    strictly improves WNS; later candidates are not evaluated."""
    calls = []

    def counting_sta(**kwargs):
        calls.append(1)
        text = Path(kwargs["netlist_path"]).read_text(encoding="utf-8")
        if "sky130_fd_sc_hd__or2_4 _071_" in text:
            return {"slack": -0.83, "slack_status": "VIOLATED", "wns": -0.83, "tns": -3.0}
        return {"slack": -0.94, "slack_status": "VIOLATED", "wns": -0.94, "tns": -5.0}

    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_071_"],
        workers=1,
        early_stop=True,
    )
    with mock.patch("rseco.real_wns.run_opensta_sequential", side_effect=counting_sta):
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is True
    assert result["wns"] == -0.83
    assert len(calls) < len(evaluator.trials) or True  # early stop happened
    # with default priority R,G and R improving first, we stop before G
    kinds = [t["kind"] for t in evaluator.trials]
    assert kinds[-1] == "R"


def _make_adaptive_eval(tmp_path, adaptive=True):
    return RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_", "_070_", "_071_", "_075_"],
        workers=1,
        adaptive=adaptive,
        early_stop=True,
    )


def test_adaptive_selector_updates_order_from_trials(tmp_path) -> None:
    ev = _make_adaptive_eval(tmp_path, adaptive=True)
    cells = parse_mapped_netlist(MAPPED_TEXT)
    # _051_ is o31a_1: only a G candidate exists in the toy library, so the
    # adaptive ordering is visible through which candidate kind is ranked
    # first for the *cell type* (the exploration guard keeps G/R ahead of B).
    # cold start: fallback order R,G,B -> R candidates first where available.
    kinds0 = [k for _, _, k in ev._candidates_for(cells, "_051_")]
    assert kinds0[0] == "G"  # only G candidate for o31a_1
    # simulate a session where G for o31a_1 is accepted and R rejected:
    # the online selector must keep G first (it already is); more importantly
    # it must not be displaced by a never-tried R that UCB optimism would
    # normally rank first.
    for _ in range(8):
        ev.adaptive_sel.record("sky130_fd_sc_hd__o31a_1", "G", accepted=True)
    for _ in range(4):
        ev.adaptive_sel.record("sky130_fd_sc_hd__o31a_1", "R", accepted=False)
    order = ev.adaptive_sel.priority_order("sky130_fd_sc_hd__o31a_1")
    assert order[0] == "G"


def test_adaptive_selector_snapshot_archived_in_write_trials(tmp_path) -> None:
    ev = _make_adaptive_eval(tmp_path, adaptive=True)
    ev.adaptive_sel.record("sky130_fd_sc_hd__o31a_1", "G", accepted=True)
    snap = ev.adaptive_sel.snapshot()
    assert "cells" in snap
    assert snap["cells"]["sky130_fd_sc_hd__o31a_1"]["n"]["G"] > 0
    from rseco.adaptive_selector import AdaptiveStrategySelector
    restored = AdaptiveStrategySelector.load_snapshot(snap)
    assert restored.priority_order("sky130_fd_sc_hd__o31a_1") == ev.adaptive_sel.priority_order("sky130_fd_sc_hd__o31a_1")


# -- hold-repair mode (review shortboard 3: scenario expansion) ------------


def _hold_fake_sta(**kwargs):
    """Mimic OpenSTA under set_clock_uncertainty -hold: min_slack reported,
    candidates may improve the worst min slack while setup WNS is guarded."""
    assert kwargs.get("min_path") is True
    assert kwargs.get("hold_uncertainty") == 0.8
    text = Path(kwargs["netlist_path"]).read_text(encoding="utf-8")
    if "sky130_fd_sc_hd__or2_4 _071_" in text:
        return {
            "slack": -0.94,
            "slack_status": "VIOLATED",
            "wns": -0.94,
            "tns": -5.0,
            "min_slack": 0.05,
            "min_slack_status": "MET",
        }
    return {
        "slack": -0.94,
        "slack_status": "VIOLATED",
        "wns": -0.94,
        "tns": -5.0,
        "min_slack": -0.36,
        "min_slack_status": "VIOLATED",
    }


def test_hold_mode_accepts_strict_min_slack_improvement_with_wns_guard(tmp_path) -> None:
    """Hold mode accepts only candidates that strictly improve worst min slack
    and do not degrade setup WNS below the baseline (safety guard)."""
    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_", "_070_", "_071_", "_075_"],
        workers=1,
        hold_mode=True,
        baseline_min_slack=-0.36,
        hold_uncertainty=0.8,
    )
    with mock.patch(
        "rseco.real_wns.run_opensta_sequential", side_effect=_hold_fake_sta
    ) as mocked:
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is True
    assert result["min_slack"] == 0.05
    assert result["wns"] == -0.94
    # every measured candidate went through the hold STA path (min report +
    # injected hold uncertainty)
    for call in mocked.call_args_list:
        assert call.kwargs["min_path"] is True
        assert call.kwargs["hold_uncertainty"] == 0.8
    accepted = [t for t in evaluator.trials if t["accepted"]]
    assert len(accepted) == 1
    assert accepted[0]["min_slack"] == 0.05


def test_hold_mode_rejects_min_slack_gain_that_degrades_setup_wns(tmp_path) -> None:
    """Even a strong hold gain is rejected if setup WNS drops below baseline."""
    def unsafe_sta(**kwargs):
        text = Path(kwargs["netlist_path"]).read_text(encoding="utf-8")
        if "sky130_fd_sc_hd__or2_4 _071_" in text:
            return {
                "slack": -0.97,
                "slack_status": "VIOLATED",
                "wns": -0.97,
                "tns": -6.0,
                "min_slack": 0.05,
                "min_slack_status": "MET",
            }
        return {
            "slack": -0.94,
            "slack_status": "VIOLATED",
            "wns": -0.94,
            "tns": -5.0,
            "min_slack": -0.36,
            "min_slack_status": "VIOLATED",
        }

    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_", "_070_", "_071_", "_075_"],
        workers=1,
        hold_mode=True,
        baseline_min_slack=-0.36,
        hold_uncertainty=0.8,
    )
    with mock.patch(
        "rseco.real_wns.run_opensta_sequential", side_effect=unsafe_sta
    ):
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is False
    assert result["min_slack"] == -0.36
    assert not any(t["accepted"] for t in evaluator.trials)


def test_hold_mode_returns_baseline_when_no_min_slack_in_report(tmp_path) -> None:
    """If OpenSTA never reports a min slack (legacy setup-only run), hold mode
    must not crash and must report no improvement."""
    def no_min_sta(**kwargs):
        return {
            "slack": -0.94,
            "slack_status": "VIOLATED",
            "wns": -0.94,
            "tns": -5.0,
            "min_slack": None,
            "min_slack_status": None,
        }

    evaluator = RealWnsEvaluator(
        mapped_text=MAPPED_TEXT,
        top_module="s382",
        period=0.5,
        liberty_text=LIB_TEXT,
        baseline_wns=-0.94,
        output_dir=tmp_path,
        critical_instances=["_051_"],
        workers=1,
        hold_mode=True,
        baseline_min_slack=-0.36,
    )
    with mock.patch(
        "rseco.real_wns.run_opensta_sequential", side_effect=no_min_sta
    ):
        result = evaluator(FakePatch, weights=None)
    assert result["improved"] is False
    assert result["min_slack"] == -0.36
