/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module c17_original(N1, N2, N3, N6, N7, N22, N23);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input N1;
  wire N10;
  wire N11;
  wire N16;
  wire N19;
  input N2;
  output N22;
  output N23;
  input N3;
  input N6;
  input N7;
  sky130_fd_sc_hd__nand2_1 _20_ (
    .A(_02_),
    .B(_03_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o21a_1 _21_ (
    .A1(_04_),
    .A2(_01_),
    .B1(_05_),
    .X(_07_)
  );
  sky130_fd_sc_hd__a22o_1 _22_ (
    .A1(_02_),
    .A2(_00_),
    .B1(_05_),
    .B2(_01_),
    .X(_06_)
  );
  assign N10 = _14_;
  assign N11 = _15_;
  assign N16 = _16_;
  assign N19 = _17_;
  assign N22 = _18_;
  assign N23 = _19_;
  assign _19_ = _07_;
  assign _18_ = _06_;
  assign _04_ = N7;
  assign _01_ = N2;
  assign _02_ = N3;
  assign _03_ = N6;
  assign _00_ = N1;
endmodule
